### ISSUE TITLE
implement tokenizer for elasticsearch

### ISSUE THREAD

**Issue by wires** [histograph/tokenizer#1]
Need input to how it should work

**Comment by bertspaan** [comment]
See https://github.com/histograph/api/issues/63

**Comment by wires** [comment]
Seems very hard to do properly ... lots of stuff in the literature; we should probably first have a look at this series...

https://www.worldcat.org/title/advances-in-information-retrieval-35th-european-conference-on-ir-research-ecir-2013-moscow-russia-march-24-27-2013-proceedings/oclc/834525798

Can also look at "google place API" for inspiration... (just putting some links here for future reference)

- https://developers.google.com/places/webservice/search?hl=en
- google places URIs https://developers.google.com/places/place-id

Anyway, I will implemented

- `_all` field histograph/core#54
- n-gram indexed search histograph/core#53
- working lucene query string histograph/api#63

closing for now
